### ISSUE TITLE
Slot_type seems to be ignored when provisioning nodes

### ISSUE THREAD

**Issue by JPchico** [Azure/cyclecloud-pbspro#10]
I have a cyclecloud cluster generated from a modified version of the PBSpro template. In it I have  added different types of nodes for execution, such as memory optimized nodes and HPC nodes for heavy duty numerical simulations.

When scheduling a job making use of the `#PBS -l slot_type=name_slot` I have found that sometimes resources are allocated that do not match the configuration of the slot. The number of nodes and processes per node is respected but the actual type of node is not. Which can result in reduced performance for certain applications.

**Comment by anhoward** [comment]
This is a known bug that should be fixed in the next release. You can use `nodearray = <arrayname>` for now as a workaround.

**Comment by anhoward** [comment]
Just to add more detail, it was fixed with this commit and will be part of release 1.3.0 of the project: https://github.com/Azure/cyclecloud-pbspro/commit/01f2c872154b60e3a2a32048bc26ca57561bc923
