### ISSUE TITLE
azpbs remove_nodes doesn't remove them from pbsnodes

### ISSUE THREAD

**Issue by mvrequa** [Azure/cyclecloud-pbspro#27]
To repro, manually add nodes to pbs cluster with add nodes in the UI. They get joined to the cluster. Then remove them with:

`azpbs remove_nodes -H ip-0A010907 -H ip-0A010908  --force`

Note that `--force` is required. They seem to temporarily go through the "down state" but recover to free.

Does this command work?

```
[root@ip-0A010906 ~]# pbsnodes -aS
vnode           state           OS       hardware host            queue        mem     ncpus   nmics   ngpus  comment
--------------- --------------- -------- -------- --------------- ---------- -------- ------- ------- ------- ---------
ip-0A010907     down            --       --       ip-0a010907     --              4gb       1       0       0 --
ip-0A010908     state-unknown   --       --       ip-0a010908     --              4gb       1       0       0 --
[root@ip-0A010906 ~]# pbsnodes -aS
vnode           state           OS       hardware host            queue        mem     ncpus   nmics   ngpus  comment
--------------- --------------- -------- -------- --------------- ---------- -------- ------- ------- ------- ---------
ip-0A010907     free            --       --       ip-0a010907     --              4gb       1       0       0 --
ip-0A010908     initializing    --       --       ip-0a010908     --              4gb       1       0       0 --
```

**Comment by ryanhamel** [comment]
First, you can pass in a list of hostnames using a comma to separate them
azpbs remove_nodes -H ip-0A010907,ip-0A010908 --force
Second, force is required if azpbs either sees a job running on the node or has matched a job to eventually run on that node.

However - if you still have the autoscale hook running, these nodes will be added once again. You can disable this running "qmgr -c 'set hook autoscale enabled=false"

Also, note: if you you want to remove them _and_ delete them (terminate the VM), use delete_nodes.

**Comment by ryanhamel** [comment]
Closing as I can not reproduce.
