### ISSUE TITLE
Job History is not in release 2.0.2

### ISSUE THREAD

**Issue by xpillons** [Azure/cyclecloud-pbspro#32]
it seems that that version doesn't contains this fix despite what is claimed in the release page
repro :
wget https://github.com/Azure/cyclecloud-pbspro/releases/download/2.0.2/cyclecloud-pbspro-pkg-2.0.2.tar.gz
tar xvf cyclecloud-pbspro-pkg-2.0.2.tar.gz
initialize_pbs.sh doesn't contains the job history parameter.

**Comment by ryanhamel** [comment]
This is fixed in 2.0.3.
