### ISSUE TITLE
hwloc-libs RPM is no longer provided in the epel repo CentOS 8

### ISSUE THREAD

**Issue by mvrequa** [Azure/cyclecloud-pbspro#33]
openpbs installers failing with missing package hwloc-libs. This is impacting CentOS 8. 

work around is do download from alma linux:
    - wget -O /tmp/hwloc-libs-1.11.9-3.el8.x86_64.rpm wget https://repo.almalinux.org/almalinux/8.3-beta/BaseOS/x86_64/os/Packages/hwloc-libs-1.11.9-3.el8.x86_64.rpm
    - yum install -y /tmp/hwloc-libs-1.11.9-3.el8.x86_64.rpm
    - rm -f /tmp/hwloc-libs-1.11.9-3.el8.x86_64.rpm

Can we redistribute in release artifacts?

**Comment by Klaas-** [comment]
do you have a strict dependency on hwloc-libs-1.11 ? CentOS 8 includes hwloc-libs-2.2.0-2.el8.x86_64.rpm directly from base, that is why it's no longer in epel http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/Packages/hwloc-libs-2.2.0-2.el8.x86_64.rpm

**Comment by Norky** [comment]
The dependency is in OpenPBS as provided by CycleCloud v8.1 (I don **think** the fault is present in v8.2). It requires a specific older version of libhwloc, while CentOS 8 provides a newer version. This error is thrown during the initial set up of a cluster freshly created:
Unable to execute command `dnf -y install /opt/cycle/jetpack/system/chef/cache/jetpack/downloads/openpbs-server-20.0.1-0.x86_64.rpm` (exit code 1)
Software Configuration
Get more help on this issue
Detail:

STDOUT: Last metadata expiration check: 0:05:19 ago on Thu 02 Sep 2021 01:56:31 PM UTC.
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
STDERR: Error: 
 Problem: conflicting requests
  - nothing provides libhwloc.so.5()(64bit) needed by openpbs-server-20.0.1-0.x86_64
EXCEPTION: dnf_package[openpbs-server-20.0.1-0.x86_64.rpm] (pbspro::server line 25) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'

**Comment by Norky** [comment]
As an update, libhwloc.so.5()(64bit) might be available from compat-hwloc1 but that doesn't appear to be called in by dnf.
